# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.2.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.2.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wizmann/Code/SimpleDBChallenge

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wizmann/Code/SimpleDBChallenge

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.2.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.2.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wizmann/Code/SimpleDBChallenge/CMakeFiles /Users/wizmann/Code/SimpleDBChallenge/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wizmann/Code/SimpleDBChallenge/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SimpleDBChallenge

# Build rule for target.
SimpleDBChallenge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SimpleDBChallenge
.PHONY : SimpleDBChallenge

# fast build rule for target.
SimpleDBChallenge/fast:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/build
.PHONY : SimpleDBChallenge/fast

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/main.cpp.s
.PHONY : main.cpp.s

src/Command.o: src/Command.cpp.o
.PHONY : src/Command.o

# target to build an object file
src/Command.cpp.o:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/src/Command.cpp.o
.PHONY : src/Command.cpp.o

src/Command.i: src/Command.cpp.i
.PHONY : src/Command.i

# target to preprocess a source file
src/Command.cpp.i:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/src/Command.cpp.i
.PHONY : src/Command.cpp.i

src/Command.s: src/Command.cpp.s
.PHONY : src/Command.s

# target to generate assembly for a file
src/Command.cpp.s:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/src/Command.cpp.s
.PHONY : src/Command.cpp.s

src/Database.o: src/Database.cpp.o
.PHONY : src/Database.o

# target to build an object file
src/Database.cpp.o:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/src/Database.cpp.o
.PHONY : src/Database.cpp.o

src/Database.i: src/Database.cpp.i
.PHONY : src/Database.i

# target to preprocess a source file
src/Database.cpp.i:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/src/Database.cpp.i
.PHONY : src/Database.cpp.i

src/Database.s: src/Database.cpp.s
.PHONY : src/Database.s

# target to generate assembly for a file
src/Database.cpp.s:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/src/Database.cpp.s
.PHONY : src/Database.cpp.s

src/Handle.o: src/Handle.cpp.o
.PHONY : src/Handle.o

# target to build an object file
src/Handle.cpp.o:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/src/Handle.cpp.o
.PHONY : src/Handle.cpp.o

src/Handle.i: src/Handle.cpp.i
.PHONY : src/Handle.i

# target to preprocess a source file
src/Handle.cpp.i:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/src/Handle.cpp.i
.PHONY : src/Handle.cpp.i

src/Handle.s: src/Handle.cpp.s
.PHONY : src/Handle.s

# target to generate assembly for a file
src/Handle.cpp.s:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/src/Handle.cpp.s
.PHONY : src/Handle.cpp.s

src/Printer.o: src/Printer.cpp.o
.PHONY : src/Printer.o

# target to build an object file
src/Printer.cpp.o:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/src/Printer.cpp.o
.PHONY : src/Printer.cpp.o

src/Printer.i: src/Printer.cpp.i
.PHONY : src/Printer.i

# target to preprocess a source file
src/Printer.cpp.i:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/src/Printer.cpp.i
.PHONY : src/Printer.cpp.i

src/Printer.s: src/Printer.cpp.s
.PHONY : src/Printer.s

# target to generate assembly for a file
src/Printer.cpp.s:
	$(MAKE) -f CMakeFiles/SimpleDBChallenge.dir/build.make CMakeFiles/SimpleDBChallenge.dir/src/Printer.cpp.s
.PHONY : src/Printer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SimpleDBChallenge"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Command.o"
	@echo "... src/Command.i"
	@echo "... src/Command.s"
	@echo "... src/Database.o"
	@echo "... src/Database.i"
	@echo "... src/Database.s"
	@echo "... src/Handle.o"
	@echo "... src/Handle.i"
	@echo "... src/Handle.s"
	@echo "... src/Printer.o"
	@echo "... src/Printer.i"
	@echo "... src/Printer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

